### ISSUE TITLE
Enable NRT

### ISSUE THREAD

**Issue by chesh111re** [plneto/Synology.Api.Client#13]
Hello!
How do you feel about enabling NRT in projects, increasing c# version and maybe changing dependency by .netstandard 2.0?

**Comment by plneto** [comment]
I think that would be a great idea. It looks like it's possible to enable NRT and still use `netstandard2.0`. See https://www.meziantou.net/how-to-use-nullable-reference-types-in-dotnet-standard-2-0-and-dotnet-.htm

Please feel free to submit a PR or I'll take a look when I have some time.

**Comment by chesh111re** [comment]
Why do you want to continue using .netstandard 2.0? Is there a project with an addiction?

**Comment by plneto** [comment]
Yes, I still need it for a project and I think many other projects are still using older versions of .NET

I've just published a new version that supports NRT. Now we just need to fix the warnings in the code.
