### ISSUE TITLE
When the file name contains UTF-8 characters, the file name is incorrect.

### ISSUE THREAD

**Issue by TongRay** [plneto/Synology.Api.Client#16]
When I upload a file with UTF-8 encoded characters in the file name, the file name in FileStation becomes "=utf-8?B?XXXX?=" instead of a normal UTF-8 string.

For example, if the file name is "文件.xlsx", it will be displayed as "=utf-8?B?5paH5Lu2Lnhsc3g=?=" in FileStation.

I tried to use Postman and Restsharp V106.15, and they both got the correct result. So I think it might be because the FileName in StreamContent.Headers.ContentDisposition is encoded, which makes it unreadable by the Synology server.

Thank you very much for taking the time to look into this issue. It is greatly appreciated.

**Comment by plneto** [comment]
Thanks for reporting the issue. Would you be able to open a PR or maybe send a code snippet with a fix?

**Comment by plneto** [comment]
I've published a new version with a fix for this issue. Let me know if it's working for you now.

**Comment by TongRay** [comment]
> I've published a new version with a fix for this issue. Let me know if it's working for you now.

Thank you for the fix! Everything seems to be working smoothly now.
