### ISSUE TITLE
Authorization error when running the DownloadStationApi_DownloadStation_ListTasks() test

### ISSUE THREAD

**Issue by ikocs** [plneto/Synology.Api.Client#3]
Found an error while trying to run the test. I use a special account that only has access to DownloadStation on DSM.  When I run the test `DownloadStationApi_DownloadStation_ListTasks()`, it tries to log in to my NAS, but the request is formed as follows (WireShark data):
```http
GET /webapi/auth.cgi?api=SYNO.API.Auth&version=3&method=login&account=XXX&passwd=XXX&format=sid&otp_code=&session=FileStation
```
In theory, the field should be `session = DownloadStation`. 

In my case, an error occurs (because my special account does not have access to FileStation):
```
System.AggregateException
One or more errors occurred. (The Synology API Request failed.
Error Code: "400"
Error Description: "No such account or incorrect password"
API: "SYNO.API.Auth" 
Method: "login" 
Version: "3")
```

I would like to try to prepare a merge request, but I can’t figure out where this part of the request for authorization is formed.

**Comment by plneto** [comment]
I think you can achieve what you are trying to do by updating the API info object. You can also update the version if needed. The only downside is that you need to update each API individually. Please feel free to open a PR if you can think of a nicer way to update it.

Something like this
```
var client = new SynologyClient("URL");
            
client.ApisInfo.AuthApi.SessionName = "DownloadStation";
```

The default api info is set on the `SynologyClient.cs` file on line 43.

**Comment by ikocs** [comment]
Thank you! Understood, it turned out to carry out authorization and successfully pass the test.

I'm thinking about a more universal way of authorization. This [document](https://global.download.synology.com/download/Document/Software/DeveloperGuide/Os/DSM/All/enu/DSM_Login_Web_API_Guide_enu.pdf) seems to help. I'll try to submit a pull request soon.

**Comment by plneto** [comment]
I see. The document you linked uses DownloadStation and this [document](https://global.download.synology.com/download/Document/Software/DeveloperGuide/Package/FileStation/All/enu/Synology_File_Station_API_Guide.pdf) uses FileStation for the Login request. 

Maybe the Login method from this library could have an option to choose which session name to use.

**Comment by ikocs** [comment]
Create pull request  #4

**Comment by plneto** [comment]
Thanks. I've merged your PR.
