### ISSUE TITLE
Login fails (wrong path)

### ISSUE THREAD

**Issue by FroggieFrog** [plneto/Synology.Api.Client#6]
I had to adjust the `Path` for `AuthApi`.
According to the [official document](https://global.download.synology.com/download/Document/Software/DeveloperGuide/Package/FileStation/All/enu/Synology_File_Station_API_Guide.pdf) the `path` is `auth.cgi` instead of `entry.cgi`.

Workaround:
```csharp
const string dsmUrl = "http://192.168.0.1:5001/";

var client = new SynologyClient(dsmUrl);

//the actual workaround
client .ApisInfo.AuthApi.Path = "auth.cgi";

await client.LoginAsync("username", "password");
```

**Comment by plneto** [comment]
This path was updated in the last version. See the issue and PR below

https://github.com/plneto/Synology.Api.Client/issues/3
https://github.com/plneto/Synology.Api.Client/pull/4

I tested both `auth.cgi` and `entry.cgi` on version `DSM 7.1.1-42962 Update 3` and I was able to login.

What version of DSM do you use? Do you know more about how these paths work? There seems to be an inconsistency in the documentation between the different PDFs [FileStation API Guide](https://global.download.synology.com/download/Document/Software/DeveloperGuide/Package/FileStation/All/enu/Synology_File_Station_API_Guide.pdf), [DownloadStation API Guide](https://global.download.synology.com/download/Document/Software/DeveloperGuide/Package/DownloadStation/All/enu/Synology_Download_Station_Web_API.pdf), and [Login Web API Guide](https://global.download.synology.com/download/Document/Software/DeveloperGuide/Os/DSM/All/enu/DSM_Login_Web_API_Guide_enu.pdf)

**Comment by FroggieFrog** [comment]
Actually there seems to be a difference between DSM 6 and 7.
A **DSM 6** version required `auth.cgi` and a **DSM 7** version required `entry.cgi`.

I fixed it by checking the available API information and changing the path if necessary. Maybe this could be implemented int his library?

```csharp
var apiInfo = await _synologyClient.InfoApi().QueryAsync();
if (!string.Equals(apiInfo.AuthApi.Path, _synologyClient.ApisInfo.AuthApi.Path, StringComparison.OrdinalIgnoreCase))
{
    _synologyClient.ApisInfo.AuthApi.Path = apiInfo.AuthApi.Path;
}
```

**Comment by plneto** [comment]
I've modified the code so it always uses the paths from the InfoApi response for all APIs. This should fix the problem for everyone. Let me know if it doesn't work for you.
