### ISSUE TITLE
How to ignore certificate validation

### ISSUE THREAD

**Issue by FroggieFrog** [plneto/Synology.Api.Client#7]
Because it could be useful for others it could be good to add some documentation on how to ignore certificate validation for e.g. self signed certificates.

Basically you need to inject your own `HttpClient` with a modified `HttpClientHandler`.

```csharp
const string dsmUrl = "http://192.168.0.1:5001/";

var handler = new HttpClientHandler();
//This disables all certificate validation. It is not recommended (especially in production)!
handler.ServerCertificateCustomValidationCallback = (message, cert, chain, errors) => true;

var httpClient = new HttpClient(handler);

var client = new SynologyClient(dsmUrl, httpClient);
```

**Comment by plneto** [comment]
Sounds good. I've added your example to the to the README file. Thanks
